---
- name: Check services state
  service_facts:

- name: Ensure tzdata and ntp are installed
  apt:
    pkg: ['tzdata', 'ntp']
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure timezone
  timezone:
    name: "{{ timezone_zone }}"
  notify:
    - Reconfigure tzdata
    - Restart cron
