---
- name: Reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Restart cron
  service:
    name: cron
    state: restarted
  register: unused_disable
  failed_when: "unused_disable | failed and 'find' not in unused_disable.msg and 'found' not in unused_disable.msg"
